version: "3"
services:
  dev-db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=weroad-dev

  dev-api:
    build: ./api
    depends_on:
      - dev-db
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:secret@dev-db:5432/weroad-dev
      - ACCESS_TOKEN_SECRET=some-very-long-and-complicated-secret
      - REFRESH_TOKEN_SECRET=some-other-very-long-and-complicated-secret

  dev-web:
    build:
      context: web
      dockerfile: Dockerfile
      args:
        BASE_URL: http://localhost:3001
    depends_on:
      - dev-api
    ports:
      - "3000:3000"

volumes:
  db_data: ~